---
title: "Publications and Other Work"
editor: visual
---

## Peer-Reviewed Publications

**Xiao, B., Zhao, H., Hein‐Salvi, C., Parent, N., & Shapka, J. D.** (2025).\
*Exploring the trajectories of problematic smartphone use in adolescence: Insights from a longitudinal study.*\
**British Journal of Developmental Psychology, 43(4)**, 1010–1026.\
<https://doi.org/10.1111/bjdp.12570>

**Xiao, B., Zhao, H., Hein-Salvi, C., Parent, N!, & Shapka, J. D.** (2024).\
*Examining Self-Regulation and Problematic Smartphone Use in Canadian Adolescents: A Parallel Latent Growth Modeling Approach.*\
**Journal of Youth and Adolescence.**\
<https://doi.org/10.1007/s10964-024-02071-x>

**Xiao, B!, Parent, N., Hein-Salvi, C!, & Shapka, J. D.** (2023).\
*Shyness and problematic internet use among adolescents and young adults: A systematic review and meta‐analysis.*\
**Cogent Mental Health, 2(1).**\
<https://doi.org/10.1080/28324765.2023.2278879>

**Parent, N., Xiao, B., Hein-Salvi, C., & Shapka, J. D.** (2022).\
*Should We Be Worried about Smartphone Addiction? An Examination of Canadian Adolescents’ Feelings of Social Disconnection in the Time of COVID-19.*\
**International Journal of Environmental Research and Public Health, 19(15),** 9365.\
<https://doi.org/10.3390/ijerph19159365>

## Refereed Conference Presentations

**Hein-Salvi, C.,** Xiao, B., Zhao, H., Sam, J., & Shapka, J. (2025, November). *Scroll to the Top: A Longitudinal Examination of Popularity as a Predictor of Problematic Smartphone Use* \[Conference presentation\]. Presented at the 13th World Congress on Adolescent Health, International Association for Adolescent Health (IAAH), Jamaica

**Hein-Salvi, C.,** Xiao, B., Zhao, H., Hussey, R., Biferie, M., Sam, J., & Shapka, J. (July 2025). *Securing status and sexts: A longitudinal study examining the predictors of sexting behaviours* \[Conference poster\]. Presented at the 19th European Congress of Psychology, Paphos, Cyprus.

Sam, J., Zhao, H., Xiao, B., **Hein-Salvi, C.,** Biferie, M., Hussey, R., & Shapka, J. D. (July 2025). *Transforming adolescent mental health: The role of temperament and restrictions on device use* \[Conference presentation\]. Presented at the 19th European Congress of Psychology, Paphos, Cyprus.

Xiao, B., Zhao, H., **Hein-Salvi, C.,** Parent, N., Sam, J., & Shapka, J. (July 2025). *Exploring the trajectories of problematic smartphone use in adolescence: Insights from a longitudinal study* \[Conference poster\]. Presented at the 19th European Congress of Psychology, Paphos, Cyprus.

Zhao H., Sam J., Xiao B., Biferie M., **Hein-Salvi C.,** Hussey R., & Shapka J. (July 2025). *An exploration on the key risk factors of smartphone attachment among Canadian adolescents* \[Spotlight presentation\]. Presented at the 19th European Congress of Psychology, Paphos, Cyprus.

Parent, N., Xiao, B., **Hein-Salvi, C.,** & Shapka, J. (April 2024). *Canadian Adolescents’ problematic smartphone use, depression and Fear of Missing Out: A Longitudinal Study*. Presented at the Society for Research on Adolescence Annual Meeting, Chicago, IL, USA.

**Hein-Salvi, C.,** Parent, N., Xiao, B., & Shapka, J. (April 2023). *Through thick and thin: A mixed-methods examination of healthy relationships and personality traits amidst COVID-19*. Presented at the Society for Research on Adolescence Annual Meeting, San Diego, CA, USA.

**Hein-Salvi, C**., Parent, N., Xiao, B., Shapka, J. (June 2022). *“Comfortably disengaged”: A mixed-methods examination of social anxiety, smartphone engagement, personality traits, and mental health in the time of COVID-19”*. Presented at the Canadian Conference on Developmental Psychology, Calgary, AB, Canada.

Hesse, C. L., Parent, N., **Hein-Salvi, C**., Shapka, J. (November 2021). *Sending Nudes: Motivations behind sexting behaviours among adolescents*. Presented at the APA Technology, Mind, & Society 2021 Conference, Virtual.

**Hein-Salvi, C**., Lim, S., Angelica, B., Baeyae, J., Yu, I., Zhang, X. (May 2021). *Monkey See, Monkey Do: Does Wearing a Face Mask Increase Pro-sociality in Others?* Poster accepted to the UBC Psychology Undergraduate Research Conference (PURC), Virtual.
